export const NAVIGATE_DOWN = 'NAVIGATE_DOWN';
export const NAVIGATE_UP = 'NAVIGATE_UP';
export const NAVIGATE_LEFT = 'NAVIGATE_LEFT';
export const NAVIGATE_RIGHT = 'NAVIGATE_RIGHT';
export const REGISTER_ITEMS = 'REGISTER_ITEMS';
export const UNREGISTER_ITEMS = 'UNREGISTER_ITEMS';
